config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  resources :books
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	def self.search(term)
		where('LOWER(title) LIKE :term OR LOWER(author) LIKE :term', term: "%#{term.downcase}%")
	end
end

app/models/search_suggestion.rb
class SearchSuggestion < ApplicationRecord
	def self.terms_for(prefix)
    	$redis.zrevrange("search-suggestion:#{prefix.downcase}", 0, 9)
  	end

  	def self.index_books
	  Book.find_each do |book|
	    index_term(book.title)
	    book.title.split.each { |term| index_term(term) }
	  end
	end

	def self.index_term(term)
	  1.upto(term.length - 1) do |n|
	    prefix = term[0, n]
	    $redis.zincrby("search-suggestion:#{prefix.downcase}", 1, term.downcase)
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:search].present?
      @books = Book.search(params[:search])
    else
      @books = Book.all
    end
    # respond_to do |format|
    #   format.html
    #   format.json { @books = Book.search(params[:term]) }
    # end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :price, :published_at, :image_url)
    end
end

app/controllers/search_suggestions_controller.rb
class SearchSuggestionsController < ApplicationController
  before_action :set_search_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /search_suggestions
  # GET /search_suggestions.json
  def index
    # @search_suggestions = SearchSuggestion.all
    render json: SearchSuggestion.terms_for(params[:term])
  end

  # GET /search_suggestions/1
  # GET /search_suggestions/1.json
  def show
  end

  # GET /search_suggestions/new
  def new
    @search_suggestion = SearchSuggestion.new
  end

  # GET /search_suggestions/1/edit
  def edit
  end

  # POST /search_suggestions
  # POST /search_suggestions.json
  def create
    @search_suggestion = SearchSuggestion.new(search_suggestion_params)

    respond_to do |format|
      if @search_suggestion.save
        format.html { redirect_to @search_suggestion, notice: 'Search suggestion was successfully created.' }
        format.json { render :show, status: :created, location: @search_suggestion }
      else
        format.html { render :new }
        format.json { render json: @search_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_suggestions/1
  # PATCH/PUT /search_suggestions/1.json
  def update
    respond_to do |format|
      if @search_suggestion.update(search_suggestion_params)
        format.html { redirect_to @search_suggestion, notice: 'Search suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @search_suggestion }
      else
        format.html { render :edit }
        format.json { render json: @search_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_suggestions/1
  # DELETE /search_suggestions/1.json
  def destroy
    @search_suggestion.destroy
    respond_to do |format|
      format.html { redirect_to search_suggestions_url, notice: 'Search suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_suggestion
      @search_suggestion = SearchSuggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_suggestion_params
      params.require(:search_suggestion).permit(:term, :popularity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :published_at %>
    <%= f.datetime_select :published_at %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="row">
<% @books.each do |book| %>
  <div class="col-sm-6 col-md-4" style="width: 24.333333%;">
    <div class="thumbnail">
      <%= image_tag book.image_url %>
      <div class="caption">
        <h3 class="text-center"><%= truncate(book.title, length: 20)%></h3>
      </div>
    </div>
  </div>
<% end %> 
</div>
<script>
  // $(function() {
  //   new app.Books;
  // });
</script>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @book.published_at %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @book.image_url %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jautocomplete</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      #frm {
        margin-top:13px;
      }
    </style>
  </head>

  <body>
  	<div class="navbar navbar-default">
  		<div class="container">
  			<div class="navbar-header">
  				<a href="#" class="navbar-brand">AUTOCOMPLETE</a>
  			</div>
  			<ul class="nav navbar-nav navbar-right">
  				<li>
              <%= form_tag books_path, id: "frm", method: :get do %>
                <%= text_field_tag :search, params[:search], size: 30 %>
                <%= submit_tag "Search", name: nil %>
              <% end %>    
          </li>
  				<li><a href="#">Home</a></li>
  				<li><a href="#">Portfolio</a></li>
  				<li><a href="#">Event</a></li>
  			</ul>
  		</div>
  	</div>
  	<div class="container">
	    <%= yield %>
  	</div>
  </body>
</html>

app/views/search_suggestions/_form.html.erb
<%= form_for(search_suggestion) do |f| %>
  <% if search_suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search_suggestion.errors.count, "error") %> prohibited this search_suggestion from being saved:</h2>

      <ul>
      <% search_suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term %>
    <%= f.text_field :term %>
  </div>

  <div class="field">
    <%= f.label :popularity %>
    <%= f.number_field :popularity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/search_suggestions/edit.html.erb
<h1>Editing Search Suggestion</h1>

<%= render 'form', search_suggestion: @search_suggestion %>

<%= link_to 'Show', @search_suggestion %> |
<%= link_to 'Back', search_suggestions_path %>

app/views/search_suggestions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search Suggestions</h1>

<table>
  <thead>
    <tr>
      <th>Term</th>
      <th>Popularity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @search_suggestions.each do |search_suggestion| %>
      <tr>
        <td><%= search_suggestion.term %></td>
        <td><%= search_suggestion.popularity %></td>
        <td><%= link_to 'Show', search_suggestion %></td>
        <td><%= link_to 'Edit', edit_search_suggestion_path(search_suggestion) %></td>
        <td><%= link_to 'Destroy', search_suggestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search Suggestion', new_search_suggestion_path %>

app/views/search_suggestions/new.html.erb
<h1>New Search Suggestion</h1>

<%= render 'form', search_suggestion: @search_suggestion %>

<%= link_to 'Back', search_suggestions_path %>

app/views/search_suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @search_suggestion.term %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @search_suggestion.popularity %>
</p>

<%= link_to 'Edit', edit_search_suggestion_path(@search_suggestion) %> |
<%= link_to 'Back', search_suggestions_path %>